<?xml version="1.0" encoding="utf-8"?><Database Name="OrderSystem" Class="CustomerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=TOMPC\ORDERSYSTEM;Initial Catalog=OrderSystem;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OrderSystemConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerForename" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerSurname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerEmail" Type="System.String" DbType="VarChar(65) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerPhoneNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerAddressLine1" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerAddressLine2" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="CustomerCity" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerCounty" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerPostcode" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerPassword" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>